#include "SysCalls.h"

void initialize_sys_calls_array(){
  for (int i = 0; i < SYS_CALLS_CONUT; i++) {
    struct sys_call current_sys_call = create_sys_call_struct(i, "", 0);
    sys_calls_array[i] = current_sys_call;
  }
  set_sys_calls_names();
}

struct sys_call create_sys_call_struct(int number, char* name, int times_called){
  struct sys_call sys_call_struct;
  sys_call_struct.name = name;
  sys_call_struct.times_called = times_called;
  sys_call_struct.number = number;

  return sys_call_struct;
}

void print_sys_calls_table(){
  printf("\nNombre\t\tId\t\tVeces llamada\n");
  printf("---------------------------------------------\n");
  for (int i = 0; i < SYS_CALLS_CONUT; i++) {
    if (sys_calls_array[i].times_called > 0){
      print_sys_call_info(i);
      printf("---------------------------------------------\n");
    }
  }
  printf("Total %28d\n", 100);
}

void sys_call_seen(int sys_call_number){
  sys_calls_array[sys_call_number].times_called++;
}

void print_sys_call_info(int sys_call_number){
  struct sys_call sys_call_struct = sys_calls_array[sys_call_number];
  printf("%-16s", sys_call_struct.name);
  printf("%-16d", sys_call_struct.number);
  printf("%-16d\n", sys_call_struct.times_called);
}

struct sys_call get_sys_call(int position){
  return sys_calls_array[position];
}

int total_calls(){
  int total = 0;
  for(int i = 0; i < SYS_CALLS_CONUT; i++){
    total += sys_calls_array[i].times_called;
  }
  return total;
}

void set_sys_calls_names(){
  sys_calls_array[0].name = "read";
  sys_calls_array[1].name = "write";
  sys_calls_array[2].name = "open";
  sys_calls_array[3].name = "close";
  sys_calls_array[4].name = "stat";
  sys_calls_array[5].name = "fstat";
  sys_calls_array[6].name = "lstat";
  sys_calls_array[7].name = "poll";
  sys_calls_array[8].name = "lseek";
  sys_calls_array[9].name = "mmap";
  sys_calls_array[10].name = "mprotect";
  sys_calls_array[11].name = "munmap";
  sys_calls_array[12].name = "brk";
  sys_calls_array[13].name = "rt_sigaction";
  sys_calls_array[14].name = "rt_sigprocmask";
  sys_calls_array[15].name = "rt_sigreturn";
  sys_calls_array[16].name = "ioctl";
  sys_calls_array[17].name = "pread64";
  sys_calls_array[18].name = "pwrite64";
  sys_calls_array[19].name = "readv";
  sys_calls_array[20].name = "writev";
  sys_calls_array[21].name = "access";
  sys_calls_array[22].name = "pipe";
  sys_calls_array[23].name = "select";
  sys_calls_array[24].name = "sched_yield";
  sys_calls_array[25].name = "mremap";
  sys_calls_array[26].name = "msync";
  sys_calls_array[27].name = "mincore";
  sys_calls_array[28].name = "madvise";
  sys_calls_array[29].name = "shmget";
  sys_calls_array[30].name = "shmat";
  sys_calls_array[31].name = "shmctl";
  sys_calls_array[32].name = "dup";
  sys_calls_array[33].name = "dup2";
  sys_calls_array[34].name = "pause";
  sys_calls_array[35].name = "nanosleep";
  sys_calls_array[36].name = "getitimer";
  sys_calls_array[37].name = "alarm";
  sys_calls_array[38].name = "setitimer";
  sys_calls_array[39].name = "getpid";
  sys_calls_array[40].name = "sendfile";
  sys_calls_array[41].name = "socket";
  sys_calls_array[42].name = "connect";
  sys_calls_array[43].name = "accept";
  sys_calls_array[44].name = "sendto";
  sys_calls_array[45].name = "recvfrom";
  sys_calls_array[46].name = "sendmsg";
  sys_calls_array[47].name = "recvmsg";
  sys_calls_array[48].name = "shutdown";
  sys_calls_array[49].name = "bind";
  sys_calls_array[50].name = "listen";
  sys_calls_array[51].name = "getsockname";
  sys_calls_array[52].name = "getpeername";
  sys_calls_array[53].name = "socketpair";
  sys_calls_array[54].name = "setsockopt";
  sys_calls_array[55].name = "getsockopt";
  sys_calls_array[56].name = "clone";
  sys_calls_array[57].name = "fork";
  sys_calls_array[58].name = "vfork";
  sys_calls_array[59].name = "execve";
  sys_calls_array[60].name = "exit";
  sys_calls_array[61].name = "wait4";
  sys_calls_array[62].name = "kill";
  sys_calls_array[63].name = "uname";
  sys_calls_array[64].name = "semget";
  sys_calls_array[65].name = "semop";
  sys_calls_array[66].name = "semctl";
  sys_calls_array[67].name = "shmdt";
  sys_calls_array[68].name = "msgget";
  sys_calls_array[69].name = "msgsnd";
  sys_calls_array[70].name = "msgrcv";
  sys_calls_array[71].name = "msgctl";
  sys_calls_array[72].name = "fcntl";
  sys_calls_array[73].name = "flock";
  sys_calls_array[74].name = "fsync";
  sys_calls_array[75].name = "fdatasync";
  sys_calls_array[76].name = "truncate";
  sys_calls_array[77].name = "ftruncate";
  sys_calls_array[78].name = "getdents";
  sys_calls_array[79].name = "getcwd";
  sys_calls_array[80].name = "chdir";
  sys_calls_array[81].name = "fchdir";
  sys_calls_array[82].name = "rename";
  sys_calls_array[83].name = "mkdir";
  sys_calls_array[84].name = "rmdir";
  sys_calls_array[85].name = "creat";
  sys_calls_array[86].name = "link";
  sys_calls_array[87].name = "unlink";
  sys_calls_array[88].name = "symlink";
  sys_calls_array[89].name = "readlink";
  sys_calls_array[90].name = "chmod";
  sys_calls_array[91].name = "fchmod";
  sys_calls_array[92].name = "chown";
  sys_calls_array[93].name = "fchown";
  sys_calls_array[94].name = "lchown";
  sys_calls_array[95].name = "umask";
  sys_calls_array[96].name = "gettimeofday";
  sys_calls_array[97].name = "getrlimit";
  sys_calls_array[98].name = "getrusage";
  sys_calls_array[99].name = "sysinfo";
  sys_calls_array[100].name = "times";
  sys_calls_array[101].name = "ptrace";
  sys_calls_array[102].name = "getuid";
  sys_calls_array[103].name = "syslog";
  sys_calls_array[104].name = "getgid";
  sys_calls_array[105].name = "setuid";
  sys_calls_array[106].name = "setgid";
  sys_calls_array[107].name = "geteuid";
  sys_calls_array[108].name = "getegid";
  sys_calls_array[109].name = "setpgid";
  sys_calls_array[110].name = "getppid";
  sys_calls_array[111].name = "getpgrp";
  sys_calls_array[112].name = "setsid";
  sys_calls_array[113].name = "setreuid";
  sys_calls_array[114].name = "setregid";
  sys_calls_array[115].name = "getgroups";
  sys_calls_array[116].name = "setgroups";
  sys_calls_array[117].name = "setresuid";
  sys_calls_array[118].name = "getresuid";
  sys_calls_array[119].name = "setresgid";
  sys_calls_array[120].name = "getresgid";
  sys_calls_array[121].name = "getpgid";
  sys_calls_array[122].name = "setfsuid";
  sys_calls_array[123].name = "setfsgidsched_get_priority_min";
  sys_calls_array[124].name = "getsidsched_rr_get_interval";
  sys_calls_array[125].name = "capget";
  sys_calls_array[126].name = "capset";
  sys_calls_array[127].name = "rt_sigpending";
  sys_calls_array[128].name = "rt_sigtimedwait";
  sys_calls_array[129].name = "rt_sigqueueinfo";
  sys_calls_array[130].name = "rt_sigsuspend";
  sys_calls_array[131].name = "sigaltstack";
  sys_calls_array[132].name = "utime";
  sys_calls_array[133].name = "mknod";
  sys_calls_array[134].name = "uselib";
  sys_calls_array[135].name = "personality";
  sys_calls_array[136].name = "ustat";
  sys_calls_array[137].name = "statfs";
  sys_calls_array[138].name = "fstatfs";
  sys_calls_array[139].name = "sysfs";
  sys_calls_array[140].name = "getpriority";
  sys_calls_array[141].name = "setpriority";
  sys_calls_array[142].name = "sched_setparam";
  sys_calls_array[143].name = "sched_getparam";
  sys_calls_array[144].name = "sched_setscheduler";
  sys_calls_array[145].name = "sched_getscheduler";
  sys_calls_array[146].name = "sched_get_priority_max";
  sys_calls_array[147].name = "sched_get_priority_min";
  sys_calls_array[148].name = "sched_rr_get_interval";
  sys_calls_array[149].name = "mlock";
  sys_calls_array[150].name = "munlock";
  sys_calls_array[151].name = "mlockall";
  sys_calls_array[152].name = "munlockall";
  sys_calls_array[153].name = "munlockall";
  sys_calls_array[154].name = "modify_ldt";
  sys_calls_array[155].name = "pivot_root";
  sys_calls_array[156].name = "_sysctl";
  sys_calls_array[157].name = "prctl";
  sys_calls_array[158].name = "arch_prctl";
  sys_calls_array[159].name = "adjtimex";
  sys_calls_array[160].name = "setrlimit";
  sys_calls_array[161].name = "chroot";
  sys_calls_array[162].name = "sync";
  sys_calls_array[163].name = "acct";
  sys_calls_array[164].name = "settimeofday";
  sys_calls_array[165].name = "mount";
  sys_calls_array[166].name = "umount2";
  sys_calls_array[167].name = "swapon";
  sys_calls_array[168].name = "swapoff";
  sys_calls_array[169].name = "reboot";
  sys_calls_array[170].name = "sethostname";
  sys_calls_array[171].name = "setdomainname";
  sys_calls_array[172].name = "iopl";
  sys_calls_array[173].name = "ioperm";
  sys_calls_array[174].name = "create_module";
  sys_calls_array[175].name = "init_module";
  sys_calls_array[176].name = "delete_module";
  sys_calls_array[177].name = "get_kernel_syms";
  sys_calls_array[178].name = "query_module";
  sys_calls_array[179].name = "quotactl";
  sys_calls_array[180].name = "nfsservctl";
  sys_calls_array[181].name = "getpmsg";
  sys_calls_array[182].name = "putpmsg";
  sys_calls_array[183].name = "afs";
  sys_calls_array[184].name = "tuxcall";
  sys_calls_array[185].name = "security";
  sys_calls_array[186].name = "gettid";
  sys_calls_array[187].name = "readahead";
  sys_calls_array[188].name = "setxattr";
  sys_calls_array[189].name = "lsetxattr";
  sys_calls_array[190].name = "fsetxattr";
  sys_calls_array[191].name = "getxattr";
  sys_calls_array[192].name = "lgetxattr";
  sys_calls_array[193].name = "fgetxattr";
  sys_calls_array[194].name = "listxattr";
  sys_calls_array[195].name = "llistxattr";
  sys_calls_array[196].name = "flistxattr";
  sys_calls_array[197].name = "removexattr";
  sys_calls_array[198].name = "lremovexattr";
  sys_calls_array[199].name = "fremovexattr";
  sys_calls_array[200].name = "tkill";
  sys_calls_array[201].name = "time";
  sys_calls_array[202].name = "futex";
  sys_calls_array[203].name = "sched_setaffinity";
  sys_calls_array[204].name = "sched_getaffinity";
  sys_calls_array[205].name = "set_thread_area";
  sys_calls_array[206].name = "io_setup";
  sys_calls_array[207].name = "io_destroy";
  sys_calls_array[208].name = "io_getevents";
  sys_calls_array[209].name = "io_submit";
  sys_calls_array[210].name = "io_cancel";
  sys_calls_array[211].name = "get_thread_area";
  sys_calls_array[212].name = "lookup_dcookie";
  sys_calls_array[213].name = "epoll_create";
  sys_calls_array[214].name = "epoll_ctl_old";
  sys_calls_array[215].name = "epoll_wait_old";
  sys_calls_array[216].name = "remap_file_pages";
  sys_calls_array[217].name = "getdents";
  sys_calls_array[218].name = "set_tid_address";
  sys_calls_array[219].name = "set_tid_address";
  sys_calls_array[220].name = "semtimedop";
  sys_calls_array[221].name = "fadvise64";
  sys_calls_array[222].name = "timer_create";
  sys_calls_array[223].name = "timer_settime";
  sys_calls_array[224].name = "timer_gettime";
  sys_calls_array[225].name = "timer_getoverrun";
  sys_calls_array[226].name = "timer_delete";
  sys_calls_array[227].name = "clock_settime";
  sys_calls_array[228].name = "clock_gettime";
  sys_calls_array[229].name = "clock_getres";
  sys_calls_array[230].name = "clock_nanosleep";
  sys_calls_array[231].name = "exit_group";
  sys_calls_array[232].name = "epoll_wait";
  sys_calls_array[233].name = "epoll_ctl";
  sys_calls_array[234].name = "tgkill";
  sys_calls_array[235].name = "utimes";
  sys_calls_array[236].name = "vserver";
  sys_calls_array[237].name = "mbind";
  sys_calls_array[238].name = "set_mempolicy";
  sys_calls_array[239].name = "get_mempolicy";
  sys_calls_array[240].name = "mq_open";
  sys_calls_array[241].name = "mq_unlink";
  sys_calls_array[242].name = "mq_timedsend";
  sys_calls_array[243].name = "mq_timedreceive";
  sys_calls_array[244].name = "mq_notify";
  sys_calls_array[245].name = "mq_getsetattr";
  sys_calls_array[246].name = "kexec_load";
  sys_calls_array[247].name = "waitid";
  sys_calls_array[248].name = "add_key";
  sys_calls_array[249].name = "request_key";
  sys_calls_array[250].name = "keyctl";
  sys_calls_array[251].name = "ioprio_set";
  sys_calls_array[252].name = "ioprio_get";
  sys_calls_array[253].name = "inotify_init";
  sys_calls_array[254].name = "inotify_add_watch";
  sys_calls_array[255].name = "inotify_rm_watch";
  sys_calls_array[256].name = "migrate_pages";
  sys_calls_array[257].name = "openat";
  sys_calls_array[258].name = "mkdirat";
  sys_calls_array[259].name = "mknodat";
  sys_calls_array[260].name = "fchownat";
  sys_calls_array[261].name = "futimesat";
  sys_calls_array[262].name = "newfstatat";
  sys_calls_array[263].name = "unlinkat";
  sys_calls_array[264].name = "renameat";
  sys_calls_array[265].name = "linkat";
  sys_calls_array[266].name = "symlinkat";
  sys_calls_array[267].name = "readlinkat";
  sys_calls_array[268].name = "fchmodat";
  sys_calls_array[269].name = "faccessat";
  sys_calls_array[270].name = "pselect6";
  sys_calls_array[271].name = "ppoll";
  sys_calls_array[272].name = "unshare";
  sys_calls_array[273].name = "set_robust_list";
  sys_calls_array[274].name = "get_robust_list";
  sys_calls_array[275].name = "splice";
  sys_calls_array[276].name = "tee";
  sys_calls_array[277].name = "sync_file_range";
  sys_calls_array[278].name = "vmsplice";
  sys_calls_array[279].name = "move_pages";
  sys_calls_array[280].name = "utimensat";
  sys_calls_array[281].name = "epoll_pwait";
  sys_calls_array[282].name = "signalfd";
  sys_calls_array[283].name = "timerfd_create";
  sys_calls_array[284].name = "eventfd";
  sys_calls_array[286].name = "fallocate";
  sys_calls_array[285].name = "timerfd_settime";
  sys_calls_array[287].name = "timerfd_gettime";
  sys_calls_array[288].name = "accept";
  sys_calls_array[289].name = "signalfd";
  sys_calls_array[290].name = "eventfd";
  sys_calls_array[291].name = "epoll_create";
  sys_calls_array[292].name = "dup";
  sys_calls_array[293].name = "pipe";
  sys_calls_array[294].name = "inotify_init";
  sys_calls_array[295].name = "preadv";
  sys_calls_array[296].name = "pwritev";
  sys_calls_array[297].name = "rt_tgsigqueueinfo";
  sys_calls_array[298].name = "perf_event_open";
  sys_calls_array[299].name = "recvmmsg";
  sys_calls_array[300].name = "fanotify_init";
  sys_calls_array[301].name = "fanotify_mark";
  sys_calls_array[302].name = "prlimit64";
  sys_calls_array[303].name = "name_to_handle_at";
  sys_calls_array[304].name = "open_by_handle_at";
  sys_calls_array[305].name = "clock_adjtime";
  sys_calls_array[306].name = "syncfs";
  sys_calls_array[307].name = "sendmmsg";
  sys_calls_array[308].name = "setns";
  sys_calls_array[309].name = "getcpu";
  sys_calls_array[310].name = "process_vm_readv";
  sys_calls_array[311].name = "process_vm_writev";
  sys_calls_array[312].name = "kcmp";
  sys_calls_array[313].name = "finit_module";
  sys_calls_array[314].name = "sched_setattr";
  sys_calls_array[315].name = "sched_getattr";
  sys_calls_array[316].name = "renameat2";
  sys_calls_array[317].name = "seccomp";
  sys_calls_array[318].name = "getrandom";
  sys_calls_array[319].name = "memfd_create";
  sys_calls_array[320].name = "kexec_file_load";
  sys_calls_array[321].name = "bpf";
  sys_calls_array[322].name = "execveat";
  sys_calls_array[323].name = "userfaultfd";
  sys_calls_array[324].name = "membarrier";
  sys_calls_array[325].name = "mlock";
  sys_calls_array[326].name = "copy_file_range";
  sys_calls_array[327].name = "preadv";
  sys_calls_array[328].name = "pwritev";
  sys_calls_array[329].name = "pkey_mprotect";
  sys_calls_array[330].name = "pkey_alloc";
  sys_calls_array[331].name = "pkey_free";
  sys_calls_array[332].name = "statx";
  sys_calls_array[333].name = "io_pgetevents";
  sys_calls_array[334].name = "rseq";
}
